/**
 * generated by Xtext 2.33.0
 */
package d.fe.up.pt.cicd.gha.expressions.dsl.ghaExpressions.impl;

import d.fe.up.pt.cicd.gha.expressions.dsl.ghaExpressions.Expression;
import d.fe.up.pt.cicd.gha.expressions.dsl.ghaExpressions.GhaExpressionsPackage;
import d.fe.up.pt.cicd.gha.expressions.dsl.ghaExpressions.Not;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Not</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link d.fe.up.pt.cicd.gha.expressions.dsl.ghaExpressions.impl.NotImpl#getChildExpr <em>Child Expr</em>}</li>
 * </ul>
 *
 * @generated
 */
public class NotImpl extends ExpressionImpl implements Not
{
  /**
   * The cached value of the '{@link #getChildExpr() <em>Child Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChildExpr()
   * @generated
   * @ordered
   */
  protected Expression childExpr;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected NotImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GhaExpressionsPackage.Literals.NOT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getChildExpr()
  {
    return childExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetChildExpr(Expression newChildExpr, NotificationChain msgs)
  {
    Expression oldChildExpr = childExpr;
    childExpr = newChildExpr;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GhaExpressionsPackage.NOT__CHILD_EXPR, oldChildExpr, newChildExpr);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setChildExpr(Expression newChildExpr)
  {
    if (newChildExpr != childExpr)
    {
      NotificationChain msgs = null;
      if (childExpr != null)
        msgs = ((InternalEObject)childExpr).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GhaExpressionsPackage.NOT__CHILD_EXPR, null, msgs);
      if (newChildExpr != null)
        msgs = ((InternalEObject)newChildExpr).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GhaExpressionsPackage.NOT__CHILD_EXPR, null, msgs);
      msgs = basicSetChildExpr(newChildExpr, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GhaExpressionsPackage.NOT__CHILD_EXPR, newChildExpr, newChildExpr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GhaExpressionsPackage.NOT__CHILD_EXPR:
        return basicSetChildExpr(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GhaExpressionsPackage.NOT__CHILD_EXPR:
        return getChildExpr();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GhaExpressionsPackage.NOT__CHILD_EXPR:
        setChildExpr((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GhaExpressionsPackage.NOT__CHILD_EXPR:
        setChildExpr((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GhaExpressionsPackage.NOT__CHILD_EXPR:
        return childExpr != null;
    }
    return super.eIsSet(featureID);
  }

} //NotImpl
