name: "Workflow"
run-name: Deploy to ${{ inputs || rerere && 3 || 4 }} by @${{ github.actor }}
on:
  check_run:
    types: assigned
  workflow_run:
    branches:
      - main
  pull_request:
    paths:
      - path
  push:
    tags:
      - tag
  schedule:
    - cron: "oooooo"
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
    outputs:
      workflow_output1:
        description: "The first job output"
        value: ${{ jobs.my_job.outputs.job_output1 }}
      workflow_output2:
        description: "The second job output"
        value: ${{ jobs.my_job.outputs.job_output2 }}
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: false
permissions:
  actions: read
env:
  SERVER: production
defaults:
  run:
    shell: bash
    working-directory: ./scripts
concurrency:
  group: ${{ github.workflow }} - ${{ github.ref }}
  cancel-in-progress: true
jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    permissions:
      actions: read
    services:
      my_service:
        image: redis
        ports:
          - 6379:6379
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [10, 12, 14]
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: echo ${{ env.MY_VAR }} ${{ inputs.username.bob }}
