name: "Workflow"

on:
  schedule:
    - cron: "*/5 * * * *"

env:
  SERVER: production

defaults:
  run:
    shell: bash
    working-directory: test-pipelines/gha

jobs:
  my_first_job_a:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!A"
  my_first_job_b:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!A"
  my_second_job_a:
    runs-on: ubuntu-latest
    needs:
      - my_first_job_a
      - my_first_job_b
    steps:
      - run: echo 2
  my_second_job_b:
    runs-on: ubuntu-latest
    container: alpine:3.12
    needs: my_first_job_a
    steps:
      - run: echo ${{ env.TWO }}
        env:
          TWO: 2
      - run: echo ${{ env.FOUR }}
        env:
          FOUR: 4
  my_third_job:
    runs-on: ubuntu-latest
    needs: my_second_job_b
    steps:
      - run: echo ${{ env.TWO }}
        if: ${{env.SERVER == 'production'}}
        env:
          TWO: 2
      - run: cat "one.txt"
  my_fourth_job:
    runs-on: ubuntu-latest
    needs:
      - my_third_job
      - my_second_job_a
    steps:
      - run: echo ${{ env.TWO }}
        if: ${{env.SERVER == 'production'}}
        env:
          TWO: 2
      - run: cat "one.txt"