<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Transformations" nsURI="http://d.fe.up.pt/Transformations" nsPrefix="Transformations">
  <eClassifiers xsi:type="ecore:EClass" name="StringToStringMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformations" upperBound="-1"
        eType="#//Transformation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transformation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" lowerBound="1" eType="#//MODEL_NAMES"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MODEL_NAMES">
    <eLiterals name="CICD"/>
    <eLiterals name="GHA" value="1"/>
    <eLiterals name="CircleCI" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangePlugin" eSuperTypes="#//RefiningTransformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//StringToStringMapEntry"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//StringToStringMapEntry"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ATLRefiningScript" eSuperTypes="#//RefiningTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="script" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeAgentLabel" eSuperTypes="#//RefiningTransformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//StringToStringMapEntry"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RefiningTransformation" abstract="true"
      eSuperTypes="#//Transformation"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutplaceTransformation" eSuperTypes="#//Transformation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ReplaceAgentLabels" eSuperTypes="#//OutplaceTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labels" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
