<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Transformations" nsURI="http://d.fe.up.pt/Transformations" nsPrefix="Transformations">
  <eClassifiers xsi:type="ecore:EClass" name="StringToStringMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransformationSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preTIM" upperBound="-1"
        eType="#//TSMTransformation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onTIM" upperBound="-1"
        eType="#//Transformation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postTIM" upperBound="-1"
        eType="#//TSMTransformation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transformation" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="TIMTransformation" abstract="true" eSuperTypes="#//Transformation"/>
  <eClassifiers xsi:type="ecore:EClass" name="TSMTransformation" abstract="true" eSuperTypes="#//Transformation"/>
  <eClassifiers xsi:type="ecore:EClass" name="InplaceTransformation" abstract="true"
      eSuperTypes="#//Transformation"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutplaceTransformation" abstract="true"
      eSuperTypes="#//Transformation"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionalTransformation" abstract="true"
      eSuperTypes="#//Transformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ATLScript" eSuperTypes="#//Transformation #//TSMTransformation #//TIMTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="script" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="model" lowerBound="1" eType="#//MODELS"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangePlugin" eSuperTypes="#//InplaceTransformation #//TIMTransformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="name" lowerBound="1" eType="#//StringToStringMapEntry"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="args" upperBound="-1" eType="#//StringToStringMapEntry"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplaceAgentLabels" eSuperTypes="#//OutplaceTransformation #//TIMTransformation #//ConditionalTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="labels" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddTrigger" eSuperTypes="#//OutplaceTransformation #//TIMTransformation #//ConditionalTransformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" eType="ecore:EClass ../../d.fe.up.pt.cicd.metamodel/model/CICD.ecore#//Trigger"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JobTransformation" eSuperTypes="#//TIMTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="job" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditStep" eSuperTypes="#//JobTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewStep" eSuperTypes="#//EditStep #//OutplaceTransformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="step" lowerBound="1" eType="ecore:EClass ../../d.fe.up.pt.cicd.metamodel/model/CICD.ecore#//Step"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReplaceStep" eSuperTypes="#//NewStep"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddStep" eSuperTypes="#//NewStep"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeleteStep" eSuperTypes="#//EditStep #//InplaceTransformation"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddPorts" eSuperTypes="#//OutplaceTransformation #//TIMTransformation #//ConditionalTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ports" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetOptions" eSuperTypes="#//InplaceTransformation #//ConditionalTransformation #//TIMTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="options" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeImage" eSuperTypes="#//OutplaceTransformation #//ConditionalTransformation #//TIMTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GHATransformation" abstract="true" eSuperTypes="#//TSMTransformation"/>
  <eClassifiers xsi:type="ecore:EClass" name="CircleCITransformation" abstract="true"
      eSuperTypes="#//TSMTransformation"/>
  <eClassifiers xsi:type="ecore:EClass" name="AddExecutor" abstract="true" eSuperTypes="#//CircleCITransformation #//OutplaceTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jobName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddOrbReferenceExecutor" eSuperTypes="#//AddExecutor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orb" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executor" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetCircleCIVersion" eSuperTypes="#//CircleCITransformation #//InplaceTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SelectWorkflow" eSuperTypes="#//CircleCITransformation #//InplaceTransformation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MODELS">
    <eLiterals name="CICD"/>
    <eLiterals name="CircleCI" value="1"/>
    <eLiterals name="GHA" value="2"/>
  </eClassifiers>
</ecore:EPackage>
