/*
 * generated by Xtext 2.33.0
 */
package d.fe.up.pt.cicd.gha;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GitHubActionsStandaloneSetup extends GitHubActionsStandaloneSetupGenerated {

	public static void doSetup() {
		new GitHubActionsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
