/*
 * generated by Xtext 2.33.0
 */
package d.fe.up.pt.cicd.transformationsdsl.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import d.fe.up.pt.cicd.transformationsdsl.dsl.DSLRuntimeModule;
import d.fe.up.pt.cicd.transformationsdsl.dsl.DSLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class DSLIdeSetup extends DSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new DSLRuntimeModule(), new DSLIdeModule()));
	}
	
}
