/*
 * generated by Xtext 2.33.0
 */
package d.fe.up.pt.cicd.gha.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GitHubActionsUiModule extends AbstractGitHubActionsUiModule {

	public GitHubActionsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
