/*
 * generated by Xtext 2.33.0
 */
package d.fe.up.pt.cicd.gha.expressions.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GHAExpressionsRuntimeModule extends AbstractGHAExpressionsRuntimeModule {
}
