/*
 * generated by Xtext 2.33.0
 */
package d.fe.up.pt.cicd.gha.expressions.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class GHAExpressionsStandaloneSetup extends GHAExpressionsStandaloneSetupGenerated {

	public static void doSetup() {
		new GHAExpressionsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
