/*
 * generated by Xtext 2.33.0
 */
package d.fe.up.pt.cicd.gha.dsl.ide;


/**
 * Use this class to register ide components.
 */
public class GitHubActionsIdeModule extends AbstractGitHubActionsIdeModule {
}
